# Generated by Django 5.0.3 on 2024-03-06 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_inventory_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 6, 12, 45, 29, 792182)),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.BooleanField(default=False),
        ),
    ]
